export const experiences: Types.Experience[] = [
  {
    start: "2022",
    position: "Desenvolvedor Full Stack Pleno",
    company: "Hammer",
    href: "https://wlgrupo.com/empresa/hammer/",
  },
  {
    start: "2020",
    end: "2022",
    position: "Desenvolvedor Backend Pleno",
    company: "Procob",
    href: "https://www.procob.com/",
  },
  {
    start: "2020",
    end: "2020",
    position: "Desenvolvedor Backend",
    company: "DealerSites",
    href: "https://dealersites.com.br/",
  },
  {
    start: "2019",
    end: "2020",
    position: "Desenvolvedor Backend/Magento 2",
    company: "DigitalHub",
    href: "https://www.digitalhub.com.br/",
  },
  {
    start: "2018",
    end: "2019",
    position: "Analista de Suporte",
    company: "CrediOK",
    href: "https://crediok.com.br/",
  },
  {
    start: "2017",
    end: "2017",
    position: "Administrador de sistemas",
    company: "CentralServer",
    href: "https://www.centralserver.com/br/",
  },
  {
    start: "2015",
    end: "2017",
    position: "Suporte Técnico N2",
    company: "Quality",
    href: "https://quality.com.br/",
  },
  {
    start: "2014",
    end: "2015",
    position: "Analista de TI Jr.",
    company: "Nova Geração",
    href: "https://www.distribuidoranovageracao.com.br/",
  },
  {
    start: "2012",
    end: "2014",
    position: "Monitor de informática",
    company: "Dom Bosco",
    href: "https://dombosco-colegio-batel-curitiba.escolaseb.com.br/pt/",
  },
];
